[tool.poetry]
name = "spacy-ebooks"
version = "0.1.0"
description = ""
authors = ["Bor Hodošček <dev@bor.space>"]

[tool.poetry.dependencies]
python = "^3.9"
spacy = "^3.2.0"
EbookLib = "^0.17.1"
en-core-web-sm = {url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.2.0/en_core_web_sm-3.2.0-py3-none-any.whl"}

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-watch = "^4.2.0"
pytest-testmon = "^1.2.2"
black = {version = "^21.10b0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
